- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-all
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-oslo-tripleo-standalone
    gate:
      jobs:
        - puppet-oslo-tripleo-standalone

- job:
    name: puppet-oslo-tripleo-standalone
    parent: tripleo-puppet-ci-centos-8-standalone
    description: |
      TripleO standalone Job running basic tests
    vars:
      build_container_images: true
      featureset_override:
        run_tempest: false
        tempest_test_whitelist:
          - 'tempest.scenario.test_server_basic_ops'
        use_os_tempest: true
