- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-all
      - release-notes-jobs-python3
    check:
      jobs:
        - tripleo-ci-centos-8-standalone
    gate:
      jobs:
        - tripleo-ci-centos-8-standalone
      queue: tripleo
